version: "3"
services:
  subsc:
    tty: true
    stdin_open: true
    container_name: subsc
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
        TZ: "Asia/Seoul"
    devices:
      - "/dev/fuse"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    ports:
      - "5000:5000"